### ISSUE TITLE
tippecanoe function with Windows 10

### ISSUE THREAD

**Issue by a-brasch** [walkerke/mapboxapi#7] opened 2020-09-22 15:10 UTC
I'm having an issue using the tippecanoe() function. I am running R via a Windows 10 machine and understand that that is a bit problematic for tippecanoe; however, I followed the "Installing tippecanoe on Windows [with Cygwin]" instructions in this [ArcGIS2Mapbox GitHub article](https://github.com/GISupportICRC/ArcGIS2Mapbox). Nonetheless, I am running into an error in R: "tippecanoe is not installed.  Please visit https://github.com/mapbox/tippecanoe for installation instructions."

I assume this has something to do with tippecanoe needing to be run through the Cygwin emulator, but I am not running R in that environment (full disclosure: I'm novice when it comes to emulators and other operating systems).

Also note that I came across another possible way to [install tippecanoe on Windows using Ubuntu Linux Bash shell](https://gist.github.com/ryanbaumann/e5c7d76f6eeb8598e66c5785b677726e#:~:text=Problem,if%20you're%20on%20Windows.)

**Comment by walkerke** [comment] 2020-09-23 10:57
Thanks for the note!  I'd like to get this working if it is possible.  mapboxapi's tippecanoe "wrapper" isn't really a wrapper per se given how tippecanoe works; instead it uses `system()` and stitches together command-line arguments from R arguments.  However, I don't believe `system()` works on Windows.  

I'll try this out on my Windows machine and see what we can get working!

**Comment by sth-new** [comment] 2022-05-04 21:32
Were you ever able to find a solution to this just out of curiosity? I have encountered the same issue ;-/

**Comment by walkerke** [comment] 2022-05-09 10:21
@sth-new Hmm - I can't reproduce on Ubuntu.  What happens in R when you run `system("tippecanoe -v")`?  

@a-brasch sorry - I haven't been using a Windows computer for a while.  I just got a new one and I'm going to try to get this working on the Windows side.

**Comment by sth-new** [comment] 2022-05-26 20:43
Hi @walkerke, I just had the chance to come back to this so apologies for the late reply! When I run `system("tippecanoe -v")` I get `syntax error near unexpected token "tippecanoe -v"'` but if I just run `tippecanoe -v`, it returns `tippecanoe v1.36.0`.  

So it does seem that it's installed, but when I try to use the tippecanoe() mapboxapi function in R I get the error code `Error: tippecanoe is not installed.  Please visit https://github.com/mapbox/tippecanoe for installation instructions.`  ;-/

**Comment by walkerke** [comment] 2022-06-25 22:21
@a-brasch @sth-new @mrworthington - 

I've been digging on this and it appears to be an RStudio issue beyond the scope of mapboxapi.  In certain cases (and honestly I'm not entirely sure which ones), the output of `Sys.getenv("PATH")` is different in RStudio than it is outside of RStudio.  

I was able to resolve this by copying the printed PATH outside my RStudio then running `Sys.setenv(PATH = "xyz")` where `"xyz"` was the printed PATH.  `mapboxapi::tippecanoe()` then ran as expected.  Presumably this could be set in a user's `.Renviron`.  

I'm leaning toward not resolving this issue on the mapboxapi side and instead printing instructions on how to do this if `tippecanoe()` errors as I don't want to mess with users' PATHs.

**Comment by walkerke** [comment] 2022-06-26 15:14
I'm resolving this with the following error message: 

```
Error in `tippecanoe()`:
! tippecanoe is not installed or cannot be found by the application you are using to run mapboxapi.
• If you haven't installed tippecanoe, please visit https://github.com/mapbox/tippecanoe for installation instructions.
• If you have installed tippecanoe, run `Sys.getenv('PATH')` and make sure your application can find tippecanoe. If it cannot, adjust your PATH accordingly.
Run `rlang::last_error()` to see where the error occurred.
```

**Closed by walkerke** 2022-06-26 15:14 UTC

**Comment by a-brasch** [comment] 2022-06-27 02:48
Much appreciated @walkerke!
